### ISSUE TITLE
Will raise JSON::ParserError if response contains no JSON in body

### ISSUE THREAD

**Issue by davidcollie** [cielo24/cielo24-ruby#2]
If no JSON is present in the body or the JSON is invalid it would be preferable to raise a default `Cielo24::WebError` that includes the HTTP response code rather than `JSON::ParserError`

https://github.com/Cielo24/cielo24-ruby/blob/master/cielo24_gem/lib/cielo24/web_utils.rb#L36

**Comment by gornik** [comment]
@davidcollie Thanks for reporting the problem, the fix is on its way.
